name: Push and Deploy Serverless function
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.YAAUTH }}
        function_id: ${{ secrets.CLUEDO_ID }}
        runtime: 'python37'
        memory: '256'
        environment: DEBUG=True
        entrypoint: 'main.handler'
        source: './cluedo'
        exclude: './cluedo/tests'
