# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: PEP8 Action
      uses: quentinguidee/pep8-action@v1
    - name: Test with pytest
      run: |
        pytest

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@master
    - uses: goodsmileduck/yandex-serverless-action@v1
      with:
        token: ${{ secrets.YAAUTH }}
        function_id: ${{ secrets.CLUEDO_ID }}
        runtime: 'python37'
        memory: '256'
        environment: DEBUG=True
        entrypoint: 'main.handler'
        source: './cluedo'
        exclude: './cluedo/tests'

