name: Alice skill

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: PEP8 Action
      uses: quentinguidee/pep8-action@v1
      with:
        arguments: '--exclude=*/cluedo/tests*'
    - name: Test with pytest
      run: |
        pytest
    - name: close pull_request
      if: github.event_name == 'pull_request'
      uses: peter-evans/close-pull@v1
      with:
        comment: Auto-closing pull request
        delete-branch: true